# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-25 13:30
from __future__ import unicode_literals

import account.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendship', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends_can_subscribe', models.BooleanField(default=False)),
                ('receive_workout_notifications', models.BooleanField(default=True)),
                ('receive_workouts_from_friends', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BodyStatTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('height', models.PositiveIntegerField(default=0)),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=4)),
                ('body_fat', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('username', models.CharField(editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(blank=True, max_length=255, null=True)),
                ('lifting_weight', models.IntegerField(blank=True, null=True)),
                ('sets', models.CharField(max_length=28)),
                ('reps', models.CharField(max_length=28)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('target_muscle', models.CharField(choices=[('Back', 'Back'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Chest', 'Chest'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Shoulders', 'Shoulders')], default=1, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=60, unique=True)),
                ('exercise_rating', models.CharField(max_length=255, null=True)),
                ('target_muscle', models.CharField(max_length=255)),
                ('exercise_link', models.CharField(max_length=255, null=True)),
                ('start_exercise_image', models.CharField(max_length=255, null=True)),
                ('during_exercise_image', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['target_muscle', 'exercise_name'],
            },
        ),
        migrations.CreateModel(
            name='FriendSubscriptionSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_receive_content', models.BooleanField(default=False)),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friendship.Friend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaxLiftTracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('max_type', models.CharField(choices=[('1', '1'), ('3', '3')], max_length=255)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('target_muscle', models.CharField(editable=False, max_length=65)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Exercises')),
            ],
            options={
                'ordering': ['target_muscle', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('expiry', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('about', models.TextField(default='About', max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to=account.models.upload_to)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetMuscles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Traps', 'Traps'), ('Neck', 'Neck'), ('Biceps', 'Biceps'), ('Forearm', 'Forearm'), ('Abs', 'Abs'), ('Quads', 'Quads'), ('Calves', 'Calves'), ('Triceps', 'Triceps'), ('Lats', 'Lats'), ('Middle Back', 'Middle Back'), ('Lower Back', 'Lower Back'), ('Glutes', 'Glutes'), ('Hamstrings', 'Hamstrings'), ('Back', 'Back'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders')], default=1, max_length=2555)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for_completion', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=150)),
                ('workout_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('target_muscle', models.CharField(choices=[('Traps', 'Traps'), ('Neck', 'Neck'), ('Biceps', 'Biceps'), ('Forearm', 'Forearm'), ('Abs', 'Abs'), ('Quads', 'Quads'), ('Calves', 'Calves'), ('Triceps', 'Triceps'), ('Lats', 'Lats'), ('Middle Back', 'Middle Back'), ('Lower Back', 'Lower Back'), ('Glutes', 'Glutes'), ('Hamstrings', 'Hamstrings'), ('Back', 'Back'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders')], default=1, max_length=255)),
                ('training_type', models.CharField(choices=[('Endurance', 'Endurance'), ('Strength Training', 'Strength Training'), ('Balance Focused', 'Balance Focused'), ('Flexibility Focused', 'Flexibility Focused')], default=1, max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('sent_notification', models.BooleanField(default=False)),
                ('exercises', models.ManyToManyField(to='account.Exercise')),
                ('muscles', models.ManyToManyField(blank=True, to='account.TargetMuscles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutNotificationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_enabled', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Workout')),
            ],
        ),
        migrations.AddField(
            model_name='maxlifttracking',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercises',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Exercises'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodystattracking',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='friend_subscription_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.FriendSubscriptionSettings'),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountsettings',
            name='workout_notification_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.WorkoutNotificationSettings'),
        ),
    ]
