# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('body_fat', models.IntegerField(default=0)),
                ('gender', models.CharField(default='Male', max_length=20)),
                ('about', models.TextField(default='About', max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for_completion', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='My Workout', max_length=150)),
                ('slug', models.SlugField(max_length=255)),
                ('target_muscle', models.CharField(max_length=255)),
                ('training_type', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
