# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170323_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('notes', models.CharField(max_length=255)),
                ('exercise', models.CharField(max_length=500)),
            ],
        ),

    ]
