# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170325_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='account.Workout'),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
