# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170325_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='workout_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
