# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-02 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_exercise_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='training_type',
            field=models.CharField(choices=[('Endurance', 'Endurance'), ('Strength Training', 'Strength Training'), ('Balance Focused', 'Balance Focused'), ('Flexibility Focused', 'Flexibility Focused')], max_length=255),
        ),
    ]
