# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-03 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20170402_0802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workouts',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='training_type',
            field=models.CharField(choices=[('Endurance', 'Endurance'), ('Strength Training', 'Strength Training'), ('Balance Focused', 'Balance Focused'), ('Flexibility Focused', 'Flexibility Focused')], default=1, max_length=255),
        ),
    ]
