# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20170403_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=255)),
                ('exercise_rating', models.IntegerField()),
                ('target_muscle', models.CharField(max_length=255)),
            ],
        ),
    ]
