# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_exercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='exercise_rating',
            field=models.CharField(max_length=255),
        ),
    ]
