# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20170504_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='exercise_rating',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
