# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-14 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20170504_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='during_exercise_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='exercise_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercises',
            name='start_exercise_image',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
