# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-16 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20170514_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_image',
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_foreign_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Exercises'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
