# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 10:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20170516_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date_for_completion',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
