# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-17 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20170517_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date_for_completion',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
