# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-18 12:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20170517_0558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_foreign_id',
            new_name='exercises',
        ),
        migrations.AddField(
            model_name='exercises',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Workout'),
        ),
    ]
