# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-28 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20170518_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='account.Exercise'),
        ),
    ]
