# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-01 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20170528_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
