# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20170602_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='target_muscle',
            field=models.CharField(choices=[('Traps', 'Traps'), ('Neck', 'Neck'), ('Chest', 'Chest'), ('Biceps', 'Biceps'), ('Forearm', 'Forearm'), ('Abdominal', 'Abdominal'), ('Quads', 'Quads'), ('Calves', 'Calves'), ('Triceps', 'Triceps'), ('Lats', 'Lats'), ('Middle Back', 'Middle Back'), ('Lower Back', 'Lower Back'), ('Glutes', 'Glutes'), ('Hamstrings', 'Hamstrings')], default=1, max_length=255),
        ),
    ]
