# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-07 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_auto_20170607_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercises',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Exercises'),
        ),
    ]
